nix_version = "2.4"
disabled = [
  "empty_pattern"
]
ignore = [
    ".direnv",
    ".env",
    ".envrc",
    ".claude",
    ".zed",
    ".helix",
    ".git",
    ".gitignore",
    "flake.lock",
    ".justfile",
    ".editorconfig",
]
